const express = require('express');
const authcontroller = require('./../controllers/authcontroller');
const reviewController = require('./../controllers/TeacherContoller');
const dbInit = require('./../db');
const router = express.Router();
router.use(dbInit.dbInit);
router.route('/login').post(dbInit.login);
router.route('/addTeacher').post(authcontroller.addTeacher);
router.route('/addReview').post(reviewController.TeacherReview);
module.exports = router;